export const tableHeader = [
  {
    label: "Category",
    property: "category",
    align: "center",
    valign: "center",
    width: 40,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Vehicle No",
    property: "vehicleNo",
    align: "center",
    valign: "center",
    width: 100,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Tag No",
    property: "tagNo",
    align: "center",
    valign: "center",
    width: 60,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Entry Cam",
    property: "entryCam",
    align: "center",
    valign: "center",
    width: 90,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Exit Cam",
    property: "exitCam",
    align: "center",
    valign: "center",
    width: 90,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Entry time",
    property: "entryTime",
    align: "center",
    valign: "center",
    width: 105,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Exit time",
    property: "exitTime",
    align: "center",
    valign: "center",
    width: 105,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Duration",
    property: "duration",
    align: "center",
    valign: "center",
    width: 80,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
  {
    label: "Vehicle Status",
    property: "vehicleStatus",
    align: "center",
    valign: "center",
    width: 60,
    headerColor: "darkblue",
    headerOpacity: 1,
  },
];
